Repository gunkim/qna-service, pull requests merged in 2022-06, with the labels that each got.

#11 ✨ Question Modify 구현
  application/src/main/kotlin/io/github/gunkim/question/application/port/in/ModifyQuestionUseCase.kt
  application/src/main/kotlin/io/github/gunkim/question/application/port/out/LoadQuestionPort.kt
  application/src/main/kotlin/io/github/gunkim/question/application/port/out/ModifyQuestionPort.kt
  application/src/main/kotlin/io/github/gunkim/question/application/service/ModifyQuestionService.kt
  build.gradle.kts
  domain/src/main/kotlin/io/github/gunkim/question/domain/Question.kt
  domain/src/test/kotlin/io/github/gunkim/question/domain/QuestionTests.kt
Labels: ⚒️ 구현, ⚙️ 설정

#12 :recycle: like kotlin
  .editorconfig
  application/src/main/kotlin/io/github/gunkim/DataInitLoader.kt
  application/src/main/kotlin/io/github/gunkim/config/AuditingConfig.kt
  application/src/main/kotlin/io/github/gunkim/question/adapter/in/web/FindQuestionsController.kt
  application/src/main/kotlin/io/github/gunkim/question/adapter/out/persistence/common/BaseTimeEntity.kt
  application/src/main/kotlin/io/github/gunkim/question/adapter/out/persistence/question/QuestionJpaEntity.kt
  application/src/main/kotlin/io/github/gunkim/question/adapter/out/persistence/question/QuestionMapper.kt
  application/src/main/kotlin/io/github/gunkim/question/adapter/out/persistence/question/QuestionPersistenceAdapter.kt
  application/src/main/kotlin/io/github/gunkim/question/application/port/out/LoadQuestionPort.kt
  application/src/main/kotlin/io/github/gunkim/question/application/port/out/LoadQuestionsPort.kt
  application/src/main/kotlin/io/github/gunkim/question/application/service/FindQuestionsService.kt
  application/src/main/kotlin/io/github/gunkim/question/application/service/ModifyQuestionService.kt
  application/src/test/kotlin/io/github/gunkim/question/adapter/in/web/FindQuestionsControllerTests.kt
  application/src/test/kotlin/io/github/gunkim/question/adapter/out/persistence/QuestionMapperTests.kt
  build.gradle.kts
  domain/src/main/kotlin/io/github/gunkim/question/domain/Category.kt
  domain/src/main/kotlin/io/github/gunkim/question/domain/Question.kt
  domain/src/main/kotlin/io/github/gunkim/question/domain/Tag.kt
  domain/src/main/kotlin/io/github/gunkim/question/domain/User.kt
  domain/src/test/kotlin/io/github/gunkim/question/domain/AnswerTests.kt
  domain/src/test/kotlin/io/github/gunkim/question/domain/QuestionTests.kt
Labels: 😀 우선순위: 하

#13 ✨ Question 엔티티 업데이트 구현
  application/src/main/kotlin/io/github/gunkim/question/adapter/out/persistence/category/CategoryJpaEntity.kt
  application/src/main/kotlin/io/github/gunkim/question/adapter/out/persistence/question/QuestionJpaEntity.kt
  application/src/main/kotlin/io/github/gunkim/question/adapter/out/persistence/question/QuestionPersistenceAdapter.kt
  application/src/main/kotlin/io/github/gunkim/question/adapter/out/persistence/tag/TagJpaEntity.kt
  application/src/main/kotlin/io/github/gunkim/question/application/service/FindQuestionsService.kt
  application/src/main/kotlin/io/github/gunkim/question/application/service/ModifyQuestionService.kt
  application/src/test/kotlin/io/github/gunkim/question/adapter/out/persistence/QuestionPersistenceAdapterTests.kt
Labels: ⚒️ 구현

#15 ✨ 질문 삭제 비즈니스 구현
  application/src/main/kotlin/io/github/gunkim/question/adapter/out/persistence/question/QuestionPersistenceAdapter.kt
  application/src/main/kotlin/io/github/gunkim/question/application/port/in/DeleteQuestionUseCase.kt
  application/src/main/kotlin/io/github/gunkim/question/application/port/out/DeleteQuestionPort.kt
  application/src/main/kotlin/io/github/gunkim/question/application/service/DeleteQuestionService.kt
  application/src/test/kotlin/io/github/gunkim/question/adapter/out/persistence/QuestionPersistenceAdapterTests.kt
  application/src/test/kotlin/io/github/gunkim/question/application/service/DeleteQuestionServiceTests.kt
  domain/src/main/kotlin/io/github/gunkim/question/domain/Question.kt
Labels: ⚒️ 구현

#16 ✨ 질문 조회 비즈니스 구현 및 엔티티 도메인 변환 로직 추가
  application/src/main/kotlin/io/github/gunkim/question/adapter/out/persistence/answer/AnswerJpaEntity.kt
  application/src/main/kotlin/io/github/gunkim/question/adapter/out/persistence/question/QuestionJpaEntity.kt
  application/src/main/kotlin/io/github/gunkim/question/adapter/out/persistence/user/UserEmbedded.kt
  application/src/main/kotlin/io/github/gunkim/question/application/port/in/FindAnswerUseCase.kt
  application/src/main/kotlin/io/github/gunkim/question/application/port/out/LoadAnswerPort.kt
  application/src/main/kotlin/io/github/gunkim/question/application/service/FindAnswerService.kt
  application/src/test/kotlin/io/github/gunkim/question/adapter/in/web/FindQuestionsControllerTests.kt
  application/src/test/kotlin/io/github/gunkim/question/application/service/DeleteQuestionServiceTests.kt
  domain/src/main/kotlin/io/github/gunkim/question/domain/Question.kt
Labels: ⚒️ 구현
